default: &defaults
  check for status changes:
    cron: "* * * * *"
    # real value should be (each day @2am) >>> cron: "0 2 * * *"
    class: "CheckForStatusChangesJob"
development:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults

# don't forget to `bundle exec rake sidekiq_cron:load` in the console to refresh
# this config file | heroku: paste same bundle exec line in the Heroku Scheduler
